version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - sudo apt-get update
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo Building the project on 'date'
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo configuring nginx
      - aws s3 cp index.html s3://gbhnewbuckets3 --region us-east-1 --acl public-read
     
artifacts:
  files:
    - /var/www/html/index.html
